Added new plugin for rss reading from ADS site
sandroandrade/emile2-mobile pull request #3
Opened 2018-12-19 23:50 UTC by GugaDozero

I have added new plugin for rss reading from ADS site for reviews.

Please check it out.

2018-12-20 22:15 UTC, sandroandrade requested changes

2018-12-20 22:15 UTC, sandroandrade commented on plugins/adsnews/adsnews.qml
> +import QtQuick 2.11
Importe a versão 2.12 (Qt 5.12)

2018-12-20 22:15 UTC, sandroandrade commented on plugins/adsnews/adsnews.qml
> +import QtQuick.Controls 2.4
Importe a versão 2.12 (Qt 5.12)

2018-12-20 22:15 UTC, sandroandrade commented on plugins/adsnews/adsnews.qml
> +import QtQuick.Window 2.11
Este import é necessário?

2018-12-20 22:15 UTC, sandroandrade commented on plugins/adsnews/adsnews.qml
> +import QtQuick.XmlListModel 2.11
Verifique se está a versão mais recente do XmlListModel.

2018-12-20 22:15 UTC, sandroandrade commented on plugins/adsnews/adsnews.qml
> +
Remover esta linha em branco.

2018-12-20 22:15 UTC, sandroandrade commented on plugins/adsnews/adsnews.qml
> +        running: xmlListModel.status == XmlListModel.Loading
Use "===" em vez de "==".

2019-01-22 22:18 UTC, GugaDozero commented
Done.

2019-01-23 13:43 UTC, sandroandrade requested changes

2019-01-23 13:43 UTC, sandroandrade commented on qml.qrc
> +        <file>plugins/adsnews.json</file>
Você não deve incluir estes arquivos de plugins no .qrc. Se você fizer isso eles deixam de ser plugins porque incluir ou retirar novos plugins vai requerer que você recompile a aplicação.

2019-01-29 23:04 UTC, closed without merging